import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <header>
          <li>
            <Link href="/">
              <img className='main-img-logo' src='/imgs/mainImg/main-img.jpeg'></img>
            </Link>
          </li>
          <ol className='menu-list'>
            <li><Link href="/">home</Link></li>
            <li><Link href="/create">create</Link></li>
            <li><Link href="/read/10">read</Link></li>
          </ol>
        </header>    
        {children}
        <footer>
          footer 입니다 디자인 예정
        </footer>
      </body>
    </html>
  )
}
